import * as eks from "aws-cdk-lib/aws-eks";

/*
  The addon versions in this file are generated by the script below

  # replace the addon name with "kube-proxy", "coredns", "vpc-cni", "eks-pod-identity-agent" or "aws-ebs-csi-driver"
  ADDON_NAME=kube-proxy

  SUPPORTED_K8S_VERSION=("1.29" "1.28" "1.27" "1.26" "1.25" "1.24")

  for K8S_VERSION in ${SUPPORTED_K8S_VERSION[@]}; do \
    aws eks describe-addon-versions \
      --addon-name ${ADDON_NAME} \
      --kubernetes-version ${K8S_VERSION} \
      --output json | \
        jq '.addons[].addonVersions[0].addonVersion'
  done
*/

// kube-proxy
export const kubeProxyVersionMap: Map<eks.KubernetesVersion, string> = new Map([
  [eks.KubernetesVersion.V1_29, "v1.29.3-eksbuild.2"],
  [eks.KubernetesVersion.V1_28, "v1.28.8-eksbuild.2"],
  [eks.KubernetesVersion.V1_27, "v1.27.12-eksbuild.2"],
  [eks.KubernetesVersion.V1_26, "v1.26.15-eksbuild.2"],
  [eks.KubernetesVersion.V1_25, "v1.25.16-eksbuild.5"],
  [eks.KubernetesVersion.V1_24, "v1.24.17-eksbuild.8"],
]);

// coredns
export const coreDnsVersionMap: Map<eks.KubernetesVersion, string> = new Map([
  [eks.KubernetesVersion.V1_29, "v1.11.1-eksbuild.9"],
  [eks.KubernetesVersion.V1_28, "v1.10.1-eksbuild.11"],
  [eks.KubernetesVersion.V1_27, "v1.10.1-eksbuild.11"],
  [eks.KubernetesVersion.V1_26, "v1.9.3-eksbuild.15"],
  [eks.KubernetesVersion.V1_25, "v1.9.3-eksbuild.15"],
  [eks.KubernetesVersion.V1_24, "v1.9.3-eksbuild.15"],
]);

// vpc-cni
export const vpcCniVersionMap: Map<eks.KubernetesVersion, string> = new Map([
  [eks.KubernetesVersion.V1_29, "v1.18.1-eksbuild.3"],
  [eks.KubernetesVersion.V1_28, "v1.18.1-eksbuild.3"],
  [eks.KubernetesVersion.V1_27, "v1.18.1-eksbuild.3"],
  [eks.KubernetesVersion.V1_26, "v1.18.1-eksbuild.3"],
  [eks.KubernetesVersion.V1_25, "v1.18.1-eksbuild.3"],
  [eks.KubernetesVersion.V1_24, "v1.18.1-eksbuild.3"],
]);

// eks-pod-identity-agent
export const eksPodIdentityAgentVersionMap: Map<eks.KubernetesVersion, string> =
  new Map([
    [eks.KubernetesVersion.V1_29, "v1.2.0-eksbuild.1"],
    [eks.KubernetesVersion.V1_28, "v1.2.0-eksbuild.1"],
    [eks.KubernetesVersion.V1_27, "v1.2.0-eksbuild.1"],
    [eks.KubernetesVersion.V1_26, "v1.2.0-eksbuild.1"],
    [eks.KubernetesVersion.V1_25, "v1.2.0-eksbuild.1"],
    [eks.KubernetesVersion.V1_24, "v1.2.0-eksbuild.1"],
  ]);

// aws-ebs-csi-driver
export const ebsCsiVersionMap: Map<eks.KubernetesVersion, string> = new Map([
  [eks.KubernetesVersion.V1_29, "v1.30.0-eksbuild.1"],
  [eks.KubernetesVersion.V1_28, "v1.30.0-eksbuild.1"],
  [eks.KubernetesVersion.V1_27, "v1.30.0-eksbuild.1"],
  [eks.KubernetesVersion.V1_26, "v1.30.0-eksbuild.1"],
  [eks.KubernetesVersion.V1_25, "v1.30.0-eksbuild.1"],
  [eks.KubernetesVersion.V1_24, "v1.30.0-eksbuild.1"],
]);
